# Generated by Django 4.1.4 on 2023-01-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=100)),
                ('docemail', models.EmailField(max_length=254)),
                ('patientname', models.CharField(max_length=100)),
                ('patientemail', models.EmailField(max_length=254)),
                ('appointdate', models.DateField()),
                ('appointtime', models.TextField()),
                ('symptoms', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pass1', models.CharField(max_length=20)),
                ('pass2', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('spcl', models.CharField(max_length=50)),
                ('ava', models.CharField(max_length=50)),
            ],
        ),
    ]
