# Generated by Django 4.1.3 on 2023-01-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0003_alter_doctor_pass1_alter_doctor_pass2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='pass1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pass2',
            field=models.CharField(max_length=20),
        ),
    ]
