# Generated by Django 4.1.4 on 2023-01-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0004_alter_doctor_pass1_alter_doctor_pass2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='pass1',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='pass2',
        ),
    ]
