# Generated by Django 4.1.4 on 2023-01-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0006_remove_doctor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientname', models.CharField(max_length=50)),
                ('patientemail', models.EmailField(max_length=254, unique=True)),
                ('docname', models.CharField(max_length=50)),
                ('docemail', models.EmailField(max_length=254, unique=True)),
                ('bill', models.CharField(max_length=100)),
                ('med', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='docemail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientemail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
