# Generated by Django 4.1.4 on 2023-01-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0007_bill_alter_appointment_docemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill',
            field=models.TextField(max_length=100),
        ),
    ]
