# Generated by Django 4.1.4 on 2023-01-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0008_bill_date_time_alter_bill_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='date_time',
        ),
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
