# Generated by Django 4.1.4 on 2023-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0009_remove_bill_date_time_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='docemail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patientemail',
            field=models.EmailField(max_length=254),
        ),
    ]
