# Generated by Django 4.1.4 on 2023-01-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0010_alter_bill_docemail_alter_bill_patientemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='docemail',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientemail',
            field=models.EmailField(max_length=254),
        ),
    ]
