# Generated by Django 4.1.5 on 2023-01-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0012_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
