# Generated by Django 4.1.5 on 2023-01-07 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0013_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
