# Generated by Django 4.1.5 on 2023-01-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocApp', '0014_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
